package com.mountaincrab.logrhythm

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.SQLiteConnection
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.mountaincrab.logrhythm.data.local.ALL_MIGRATIONS
import com.mountaincrab.logrhythm.data.local.AppDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config

/**
 * Room migration tests — run on the JVM via Robolectric (no device needed).
 *
 *   ./gradlew :app:testDebugUnitTest
 *
 * IMPORTANT — schema files must exist before these tests compile.
 * Generate them by building the project at the target version:
 *   ./gradlew :app:compileDebugKotlinAndroid
 * Commit all files under app/schemas/ alongside migration code.
 *
 * MigrationTestHelper works by:
 *   1. createDatabase(name, N)  — opens a fresh DB at version N using N.json
 *   2. runMigrationsAndValidate — runs migrations then checks the resulting
 *      SQLite schema against Room's compile-time expected schema (from entity
 *      classes). Any DEFAULT-value or NOT-NULL mismatch fails the test here,
 *      before it ever reaches a user's device.
 */
@RunWith(AndroidJUnit4::class)
@Config(sdk = [34], application = android.app.Application::class)
class MigrationTest {

    companion object {
        private const val DB_NAME = "migration_test"
    }

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
    )

    /**
     * Full migration chain from v5 (the oldest schema on file) to the current
     * version. This is the most important test: any new migration must not
     * break a user upgrading from the earliest supported schema.
     *
     * Requires: app/schemas/.../5.json (already committed), and the current
     * version's schema JSON (generated by compiling the current code).
     */
    @Test
    fun migrateAllFromV5() {
        helper.createDatabase(DB_NAME, 5).close()
        helper.runMigrationsAndValidate(DB_NAME, AppDatabase.CURRENT_VERSION, true, *ALL_MIGRATIONS)
    }

    /**
     * Tests that v6→v7 adds syncStatus/updatedAt to tag tables without
     * producing DEFAULT clauses that Room 2.7 schema validation rejects.
     *
     * Requires: app/schemas/.../6.json — generate by checking out the last
     * v6 commit and running ./gradlew :app:compileDebugKotlinAndroid.
     */
    @Test
    fun migrate6To7_tagColumnsAddedCorrectly() {
        helper.createDatabase(DB_NAME, 6).apply {
            execSQL("INSERT INTO poop_tags (id, name, isDeleted, sortOrder, createdAt) VALUES ('t1', 'urgent', 0, 1, 1000000)")
            execSQL("INSERT INTO note_tags  (id, name, isDeleted, sortOrder, createdAt) VALUES ('t2', 'mood',   0, 1, 1000000)")
            close()
        }

        val db = helper.runMigrationsAndValidate(DB_NAME, 7, true, *ALL_MIGRATIONS)

        // Verify data survived and new columns carry the expected seed values.
        db.query("SELECT syncStatus, updatedAt FROM poop_tags WHERE id = 't1'").use { c ->
            assertEquals(1, c.count)
            c.moveToFirst()
            assertEquals("PENDING", c.getString(0))
            assertEquals(0L, c.getLong(1))
        }
        db.query("SELECT syncStatus, updatedAt FROM note_tags WHERE id = 't2'").use { c ->
            assertEquals(1, c.count)
            c.moveToFirst()
            assertEquals("PENDING", c.getString(0))
            assertEquals(0L, c.getLong(1))
        }
        db.close()
    }

    /**
     * Tests that v7→v8 (the schema-repair migration) leaves data intact and
     * produces a schema that passes Room's validation. This migration exists
     * to fix devices that ran the original MIGRATION_6_7 (ALTER TABLE variant)
     * before it was corrected to use table recreation.
     *
     * Requires: app/schemas/.../7.json.
     */
    @Test
    fun migrate7To8_dataPreserved() {
        helper.createDatabase(DB_NAME, 7).apply {
            execSQL("INSERT INTO poop_tags VALUES ('t1', 'urgent', 0, 1, 1000000, 9999, 'SYNCED')")
            execSQL("INSERT INTO note_tags  VALUES ('t2', 'mood',   0, 1, 1000000, 8888, 'PENDING')")
            close()
        }

        val db = helper.runMigrationsAndValidate(DB_NAME, 8, true, *ALL_MIGRATIONS)

        db.query("SELECT syncStatus, updatedAt FROM poop_tags WHERE id = 't1'").use { c ->
            c.moveToFirst()
            assertEquals("SYNCED", c.getString(0))
            assertEquals(9999L, c.getLong(1))
        }
        db.query("SELECT syncStatus, updatedAt FROM note_tags WHERE id = 't2'").use { c ->
            c.moveToFirst()
            assertEquals("PENDING", c.getString(0))
            assertEquals(8888L, c.getLong(1))
        }
        db.close()
    }

    /**
     * Tests that v11→v12 splits a medication's strength into doseAmount + doseUnit and
     * carries the existing value across, so "1g" still reads as "1g" after the upgrade.
     *
     * Requires: app/schemas/.../11.json.
     */
    @Test
    fun migrate11To12_strengthMovesToDoseAmount() {
        helper.createDatabase(DB_NAME, 11).apply {
            execSQL(
                "INSERT INTO medications " +
                    "(id, userId, profileId, name, form, dose, sortOrder, createdAt, updatedAt, syncStatus, isDeleted) " +
                    "VALUES ('m1', 'u1', 'default', 'Pentasa', 'TABLET', '1g', 0, 1000, 2000, 'SYNCED', 0)",
            )
            close()
        }

        val db = helper.runMigrationsAndValidate(DB_NAME, 12, true, *ALL_MIGRATIONS)

        db.query("SELECT doseAmount, doseUnit, name, syncStatus FROM medications WHERE id = 'm1'").use { c ->
            assertEquals(1, c.count)
            c.moveToFirst()
            assertEquals("1g", c.getString(0))
            assertEquals("", c.getString(1))
            assertEquals("Pentasa", c.getString(2))
            // Reshaped rows are re-pushed so Firestore gets the new field names.
            assertEquals("PENDING", c.getString(3))
        }
        db.close()
    }

    /**
     * Tests that v12→v13 makes the catalog the single source of truth for a dose's name and
     * strength: `medication_entries` loses its snapshot columns, and the flags that must never
     * be read as "gone" become `isArchived` — carrying the old `isDeleted` value across, so an
     * already-deleted medication comes back archived rather than live.
     *
     * Requires: app/schemas/.../12.json.
     */
    @Test
    fun migrate12To13_snapshotsDroppedAndDeletionBecomesArchival() {
        helper.createDatabase(DB_NAME, 12).apply {
            execSQL(
                "INSERT INTO medications " +
                    "(id, userId, profileId, name, form, doseAmount, doseUnit, sortOrder, " +
                    "createdAt, updatedAt, syncStatus, isDeleted) " +
                    "VALUES ('m1', 'u1', 'default', 'Pentasa', 'TABLET', '1', 'g', 0, 1000, 2000, 'SYNCED', 1)",
            )
            execSQL(
                "INSERT INTO medication_schedules " +
                    "(id, userId, profileId, medicationId, quantity, timeMinutes, repeatRule, " +
                    "daysMask, startEpochDay, isActive, createdAt, updatedAt, syncStatus, isDeleted) " +
                    "VALUES ('s1', 'u1', 'default', 'm1', '2', 480, 'DAILY', 0, 20000, 1, 1000, 2000, 'SYNCED', 0)",
            )
            execSQL(
                "INSERT INTO medication_entries " +
                    "(id, userId, profileId, medicationId, medicationName, dose, quantity, " +
                    "occurredAt, scheduleId, notes, createdAt, updatedAt, syncStatus, isDeleted) " +
                    "VALUES ('s1_2026-08-19', 'u1', 'default', 'm1', 'Pentasa', '1g', '2', " +
                    "5000, 's1', null, 1000, 2000, 'SYNCED', 0)",
            )
            close()
        }

        val db = helper.runMigrationsAndValidate(DB_NAME, 13, true, *ALL_MIGRATIONS)

        db.query("SELECT isArchived, name, syncStatus FROM medications WHERE id = 'm1'").use { c ->
            assertEquals(1, c.count)
            c.moveToFirst()
            assertEquals(1, c.getInt(0))
            assertEquals("Pentasa", c.getString(1))
            // Reshaped rows are re-pushed so Firestore gets the new field names.
            assertEquals("PENDING", c.getString(2))
        }
        db.query("SELECT isArchived, isActive FROM medication_schedules WHERE id = 's1'").use { c ->
            c.moveToFirst()
            assertEquals(0, c.getInt(0))
            assertEquals(1, c.getInt(1))
        }
        // The dose keeps its id, its link and its quantity; the copied name and strength are gone.
        db.query("SELECT medicationId, quantity, scheduleId FROM medication_entries WHERE id = 's1_2026-08-19'").use { c ->
            assertEquals(1, c.count)
            c.moveToFirst()
            assertEquals("m1", c.getString(0))
            assertEquals("2", c.getString(1))
            assertEquals("s1", c.getString(2))
        }
        db.close()
    }

    /**
     * Verifies every migration overrides migrate(SQLiteConnection).
     *
     * MigrationTestHelper uses SupportSQLiteOpenHelper internally and calls
     * migrate(SupportSQLiteDatabase), so the schema tests above pass even if
     * migrate(SQLiteConnection) is missing. The production app uses
     * BundledSQLiteDriver, which calls migrate(SQLiteConnection); if that isn't
     * overridden the base class throws NotImplementedError on first migration.
     * This reflection check catches the wrong signature before it ships.
     */
    @Test
    fun allMigrations_overrideSQLiteConnectionMigrate() {
        for (migration in ALL_MIGRATIONS) {
            val method = try {
                migration.javaClass.getDeclaredMethod("migrate", SQLiteConnection::class.java)
            } catch (e: NoSuchMethodException) {
                null
            }
            assertNotNull(
                "Migration ${migration.startVersion}→${migration.endVersion} must override " +
                    "migrate(SQLiteConnection) for BundledSQLiteDriver. " +
                    "Only migrate(SupportSQLiteDatabase) was found.",
                method,
            )
        }
    }
}
