package com.mountaincrab.logrhythm

import androidx.room.testing.MigrationTestHelper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.mountaincrab.logrhythm.data.local.ALL_MIGRATIONS
import com.mountaincrab.logrhythm.data.local.AppDatabase
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config

/**
 * Room migration tests — run on the JVM via Robolectric (no device needed).
 *
 *   ./gradlew :app:testDebugUnitTest
 *
 * IMPORTANT — schema files must exist before these tests compile.
 * Generate them by building the project at the target version:
 *   ./gradlew :app:compileDebugKotlinAndroid
 * Commit all files under app/schemas/ alongside migration code.
 *
 * MigrationTestHelper works by:
 *   1. createDatabase(name, N)  — opens a fresh DB at version N using N.json
 *   2. runMigrationsAndValidate — runs migrations then checks the resulting
 *      SQLite schema against Room's compile-time expected schema (from entity
 *      classes). Any DEFAULT-value or NOT-NULL mismatch fails the test here,
 *      before it ever reaches a user's device.
 */
@RunWith(AndroidJUnit4::class)
@Config(sdk = [34], application = android.app.Application::class)
class MigrationTest {

    companion object {
        private const val DB_NAME = "migration_test"
    }

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
    )

    /**
     * Full migration chain from v5 (the oldest schema on file) to the current
     * version. This is the most important test: any new migration must not
     * break a user upgrading from the earliest supported schema.
     *
     * Requires: app/schemas/.../5.json (already committed), and the current
     * version's schema JSON (generated by compiling the current code).
     */
    @Test
    fun migrateAllFromV5() {
        helper.createDatabase(DB_NAME, 5).close()
        helper.runMigrationsAndValidate(DB_NAME, AppDatabase.CURRENT_VERSION, true, *ALL_MIGRATIONS)
    }

    /**
     * Tests that v6→v7 adds syncStatus/updatedAt to tag tables without
     * producing DEFAULT clauses that Room 2.7 schema validation rejects.
     *
     * Requires: app/schemas/.../6.json — generate by checking out the last
     * v6 commit and running ./gradlew :app:compileDebugKotlinAndroid.
     */
    @Test
    fun migrate6To7_tagColumnsAddedCorrectly() {
        helper.createDatabase(DB_NAME, 6).apply {
            execSQL("INSERT INTO poop_tags (id, name, isDeleted, sortOrder, createdAt) VALUES ('t1', 'urgent', 0, 1, 1000000)")
            execSQL("INSERT INTO note_tags  (id, name, isDeleted, sortOrder, createdAt) VALUES ('t2', 'mood',   0, 1, 1000000)")
            close()
        }

        val db = helper.runMigrationsAndValidate(DB_NAME, 7, true, *ALL_MIGRATIONS)

        // Verify data survived and new columns carry the expected seed values.
        db.query("SELECT syncStatus, updatedAt FROM poop_tags WHERE id = 't1'").use { c ->
            assertEquals(1, c.count)
            c.moveToFirst()
            assertEquals("PENDING", c.getString(0))
            assertEquals(0L, c.getLong(1))
        }
        db.query("SELECT syncStatus, updatedAt FROM note_tags WHERE id = 't2'").use { c ->
            assertEquals(1, c.count)
            c.moveToFirst()
            assertEquals("PENDING", c.getString(0))
            assertEquals(0L, c.getLong(1))
        }
        db.close()
    }

}
